/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as BookingsRouteImport } from './routes/bookings'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HostIndexRouteImport } from './routes/host.index'
import { Route as ProfilePrivacyRouteImport } from './routes/profile.privacy'
import { Route as ProfilePaymentsRouteImport } from './routes/profile.payments'
import { Route as ProfileNotificationsRouteImport } from './routes/profile.notifications'
import { Route as ProfileAboutRouteImport } from './routes/profile.about'
import { Route as PaymentBookingIdRouteImport } from './routes/payment.$bookingId'
import { Route as ListingIdRouteImport } from './routes/listing.$id'
import { Route as LegalSlugRouteImport } from './routes/legal.$slug'
import { Route as HostScanRouteImport } from './routes/host.scan'
import { Route as HostNewRouteImport } from './routes/host.new'
import { Route as HostListingsRouteImport } from './routes/host.listings'
import { Route as HostEarningsRouteImport } from './routes/host.earnings'
import { Route as HostBookingsRouteImport } from './routes/host.bookings'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as BookingBookingIdRouteImport } from './routes/booking.$bookingId'

const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsRoute = BookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HostIndexRoute = HostIndexRouteImport.update({
  id: '/host/',
  path: '/host/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilePrivacyRoute = ProfilePrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => ProfileRoute,
} as any)
const ProfilePaymentsRoute = ProfilePaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => ProfileRoute,
} as any)
const ProfileNotificationsRoute = ProfileNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => ProfileRoute,
} as any)
const ProfileAboutRoute = ProfileAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => ProfileRoute,
} as any)
const PaymentBookingIdRoute = PaymentBookingIdRouteImport.update({
  id: '/payment/$bookingId',
  path: '/payment/$bookingId',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingIdRoute = ListingIdRouteImport.update({
  id: '/listing/$id',
  path: '/listing/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalSlugRoute = LegalSlugRouteImport.update({
  id: '/legal/$slug',
  path: '/legal/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const HostScanRoute = HostScanRouteImport.update({
  id: '/host/scan',
  path: '/host/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const HostNewRoute = HostNewRouteImport.update({
  id: '/host/new',
  path: '/host/new',
  getParentRoute: () => rootRouteImport,
} as any)
const HostListingsRoute = HostListingsRouteImport.update({
  id: '/host/listings',
  path: '/host/listings',
  getParentRoute: () => rootRouteImport,
} as any)
const HostEarningsRoute = HostEarningsRouteImport.update({
  id: '/host/earnings',
  path: '/host/earnings',
  getParentRoute: () => rootRouteImport,
} as any)
const HostBookingsRoute = HostBookingsRouteImport.update({
  id: '/host/bookings',
  path: '/host/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingBookingIdRoute = BookingBookingIdRouteImport.update({
  id: '/booking/$bookingId',
  path: '/booking/$bookingId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/bookings': typeof BookingsRoute
  '/explore': typeof ExploreRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRouteWithChildren
  '/verify': typeof VerifyRoute
  '/wishlist': typeof WishlistRoute
  '/booking/$bookingId': typeof BookingBookingIdRoute
  '/category/$slug': typeof CategorySlugRoute
  '/host/bookings': typeof HostBookingsRoute
  '/host/earnings': typeof HostEarningsRoute
  '/host/listings': typeof HostListingsRoute
  '/host/new': typeof HostNewRoute
  '/host/scan': typeof HostScanRoute
  '/legal/$slug': typeof LegalSlugRoute
  '/listing/$id': typeof ListingIdRoute
  '/payment/$bookingId': typeof PaymentBookingIdRoute
  '/profile/about': typeof ProfileAboutRoute
  '/profile/notifications': typeof ProfileNotificationsRoute
  '/profile/payments': typeof ProfilePaymentsRoute
  '/profile/privacy': typeof ProfilePrivacyRoute
  '/host/': typeof HostIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/bookings': typeof BookingsRoute
  '/explore': typeof ExploreRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRouteWithChildren
  '/verify': typeof VerifyRoute
  '/wishlist': typeof WishlistRoute
  '/booking/$bookingId': typeof BookingBookingIdRoute
  '/category/$slug': typeof CategorySlugRoute
  '/host/bookings': typeof HostBookingsRoute
  '/host/earnings': typeof HostEarningsRoute
  '/host/listings': typeof HostListingsRoute
  '/host/new': typeof HostNewRoute
  '/host/scan': typeof HostScanRoute
  '/legal/$slug': typeof LegalSlugRoute
  '/listing/$id': typeof ListingIdRoute
  '/payment/$bookingId': typeof PaymentBookingIdRoute
  '/profile/about': typeof ProfileAboutRoute
  '/profile/notifications': typeof ProfileNotificationsRoute
  '/profile/payments': typeof ProfilePaymentsRoute
  '/profile/privacy': typeof ProfilePrivacyRoute
  '/host': typeof HostIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/bookings': typeof BookingsRoute
  '/explore': typeof ExploreRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRouteWithChildren
  '/verify': typeof VerifyRoute
  '/wishlist': typeof WishlistRoute
  '/booking/$bookingId': typeof BookingBookingIdRoute
  '/category/$slug': typeof CategorySlugRoute
  '/host/bookings': typeof HostBookingsRoute
  '/host/earnings': typeof HostEarningsRoute
  '/host/listings': typeof HostListingsRoute
  '/host/new': typeof HostNewRoute
  '/host/scan': typeof HostScanRoute
  '/legal/$slug': typeof LegalSlugRoute
  '/listing/$id': typeof ListingIdRoute
  '/payment/$bookingId': typeof PaymentBookingIdRoute
  '/profile/about': typeof ProfileAboutRoute
  '/profile/notifications': typeof ProfileNotificationsRoute
  '/profile/payments': typeof ProfilePaymentsRoute
  '/profile/privacy': typeof ProfilePrivacyRoute
  '/host/': typeof HostIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/bookings'
    | '/explore'
    | '/login'
    | '/profile'
    | '/verify'
    | '/wishlist'
    | '/booking/$bookingId'
    | '/category/$slug'
    | '/host/bookings'
    | '/host/earnings'
    | '/host/listings'
    | '/host/new'
    | '/host/scan'
    | '/legal/$slug'
    | '/listing/$id'
    | '/payment/$bookingId'
    | '/profile/about'
    | '/profile/notifications'
    | '/profile/payments'
    | '/profile/privacy'
    | '/host/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/bookings'
    | '/explore'
    | '/login'
    | '/profile'
    | '/verify'
    | '/wishlist'
    | '/booking/$bookingId'
    | '/category/$slug'
    | '/host/bookings'
    | '/host/earnings'
    | '/host/listings'
    | '/host/new'
    | '/host/scan'
    | '/legal/$slug'
    | '/listing/$id'
    | '/payment/$bookingId'
    | '/profile/about'
    | '/profile/notifications'
    | '/profile/payments'
    | '/profile/privacy'
    | '/host'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/bookings'
    | '/explore'
    | '/login'
    | '/profile'
    | '/verify'
    | '/wishlist'
    | '/booking/$bookingId'
    | '/category/$slug'
    | '/host/bookings'
    | '/host/earnings'
    | '/host/listings'
    | '/host/new'
    | '/host/scan'
    | '/legal/$slug'
    | '/listing/$id'
    | '/payment/$bookingId'
    | '/profile/about'
    | '/profile/notifications'
    | '/profile/payments'
    | '/profile/privacy'
    | '/host/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  BookingsRoute: typeof BookingsRoute
  ExploreRoute: typeof ExploreRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRouteWithChildren
  VerifyRoute: typeof VerifyRoute
  WishlistRoute: typeof WishlistRoute
  BookingBookingIdRoute: typeof BookingBookingIdRoute
  CategorySlugRoute: typeof CategorySlugRoute
  HostBookingsRoute: typeof HostBookingsRoute
  HostEarningsRoute: typeof HostEarningsRoute
  HostListingsRoute: typeof HostListingsRoute
  HostNewRoute: typeof HostNewRoute
  HostScanRoute: typeof HostScanRoute
  LegalSlugRoute: typeof LegalSlugRoute
  ListingIdRoute: typeof ListingIdRoute
  PaymentBookingIdRoute: typeof PaymentBookingIdRoute
  HostIndexRoute: typeof HostIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings': {
      id: '/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof BookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host/': {
      id: '/host/'
      path: '/host'
      fullPath: '/host/'
      preLoaderRoute: typeof HostIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/privacy': {
      id: '/profile/privacy'
      path: '/privacy'
      fullPath: '/profile/privacy'
      preLoaderRoute: typeof ProfilePrivacyRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/profile/payments': {
      id: '/profile/payments'
      path: '/payments'
      fullPath: '/profile/payments'
      preLoaderRoute: typeof ProfilePaymentsRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/profile/notifications': {
      id: '/profile/notifications'
      path: '/notifications'
      fullPath: '/profile/notifications'
      preLoaderRoute: typeof ProfileNotificationsRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/profile/about': {
      id: '/profile/about'
      path: '/about'
      fullPath: '/profile/about'
      preLoaderRoute: typeof ProfileAboutRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/payment/$bookingId': {
      id: '/payment/$bookingId'
      path: '/payment/$bookingId'
      fullPath: '/payment/$bookingId'
      preLoaderRoute: typeof PaymentBookingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listing/$id': {
      id: '/listing/$id'
      path: '/listing/$id'
      fullPath: '/listing/$id'
      preLoaderRoute: typeof ListingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/$slug': {
      id: '/legal/$slug'
      path: '/legal/$slug'
      fullPath: '/legal/$slug'
      preLoaderRoute: typeof LegalSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host/scan': {
      id: '/host/scan'
      path: '/host/scan'
      fullPath: '/host/scan'
      preLoaderRoute: typeof HostScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host/new': {
      id: '/host/new'
      path: '/host/new'
      fullPath: '/host/new'
      preLoaderRoute: typeof HostNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host/listings': {
      id: '/host/listings'
      path: '/host/listings'
      fullPath: '/host/listings'
      preLoaderRoute: typeof HostListingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host/earnings': {
      id: '/host/earnings'
      path: '/host/earnings'
      fullPath: '/host/earnings'
      preLoaderRoute: typeof HostEarningsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host/bookings': {
      id: '/host/bookings'
      path: '/host/bookings'
      fullPath: '/host/bookings'
      preLoaderRoute: typeof HostBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking/$bookingId': {
      id: '/booking/$bookingId'
      path: '/booking/$bookingId'
      fullPath: '/booking/$bookingId'
      preLoaderRoute: typeof BookingBookingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ProfileRouteChildren {
  ProfileAboutRoute: typeof ProfileAboutRoute
  ProfileNotificationsRoute: typeof ProfileNotificationsRoute
  ProfilePaymentsRoute: typeof ProfilePaymentsRoute
  ProfilePrivacyRoute: typeof ProfilePrivacyRoute
}

const ProfileRouteChildren: ProfileRouteChildren = {
  ProfileAboutRoute: ProfileAboutRoute,
  ProfileNotificationsRoute: ProfileNotificationsRoute,
  ProfilePaymentsRoute: ProfilePaymentsRoute,
  ProfilePrivacyRoute: ProfilePrivacyRoute,
}

const ProfileRouteWithChildren =
  ProfileRoute._addFileChildren(ProfileRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  BookingsRoute: BookingsRoute,
  ExploreRoute: ExploreRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRouteWithChildren,
  VerifyRoute: VerifyRoute,
  WishlistRoute: WishlistRoute,
  BookingBookingIdRoute: BookingBookingIdRoute,
  CategorySlugRoute: CategorySlugRoute,
  HostBookingsRoute: HostBookingsRoute,
  HostEarningsRoute: HostEarningsRoute,
  HostListingsRoute: HostListingsRoute,
  HostNewRoute: HostNewRoute,
  HostScanRoute: HostScanRoute,
  LegalSlugRoute: LegalSlugRoute,
  ListingIdRoute: ListingIdRoute,
  PaymentBookingIdRoute: PaymentBookingIdRoute,
  HostIndexRoute: HostIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
